### ISSUE TITLE
Set up Kanban Board

### ISSUE THREAD

**Issue by topeogunleye** [topeogunleye/Catalog-of-my-things#22]
### GitHub Project Link:
https://github.com/topeogunleye/catalog-of-my-things-ruby-capstone/projects/2

There are 3 people on this team.

### Team members as assigned to tasks listed:
Team member #1: @topeogunleye 
Team member #2: @afizsavage 
Team member #3: @blessedjasonmwanza

**Comment by elisha2kyakpo1** [comment]
Hi 👋 team,

You have done a great job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

### To highlight

- The board is set 👍
- The PR title and description looks professional, with all the information 👍

## Required Changes ♻️
_Check the comments under the review._

- [ ] The group task should be available and shared by team members, to share the tasks, you don't need to repeat the cards. A single card can be assigned to more than one team member. Take a look at the image to see the tasks that qualify to be group tasks.

![team](https://user-images.githubusercontent.com/53124548/160554797-6e7ec23c-dcc7-444a-955e-f7544da65046.png)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
